# Generated by Django 5.0.4 on 2024-05-30 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
