# Generated by Django 5.0.4 on 2024-04-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='meal',
            field=models.CharField(blank=True, choices=[('meat', 'Meat'), ('milk', 'milk'), ('sandwich', 'sandwich'), ('Nuggets', 'Nuggets'), ('Burger', 'Burger'), ('Pasta', 'Pasta'), ('Pie', 'Pie'), ('Pizza', 'Pizza'), ('Pancake', 'Pancake'), ('Waffle', 'Waffle')], max_length=200, null=True),
        ),
    ]
