# Generated by Django 5.0.4 on 2024-04-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0002_alter_child_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
