# Generated by Django 5.0.4 on 2024-05-30 10:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0003_alter_child_id_alter_mother_id'),
        ('teacher', '0004_delete_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='teach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teacher.teacher'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learn', models.CharField(blank=True, max_length=200, null=True)),
                ('activities', models.CharField(blank=True, choices=[('drawing and coloring', 'drawing and coloring'), ('music', 'music'), ('reading stories', 'reading stories')], max_length=200, null=True)),
                ('attiude', models.CharField(blank=True, max_length=200, null=True)),
                ('mood', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('location', models.CharField(blank=True, choices=[('arrive', 'arrive'), ('left', 'left')], max_length=200, null=True)),
                ('Important_notice', models.CharField(blank=True, max_length=200, null=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mother.child')),
            ],
        ),
    ]
