# Generated by Django 5.0.4 on 2024-06-04 10:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother', '0004_child_teach_report'),
        ('teacher', '0004_delete_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='Important_notice',
        ),
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.AddField(
            model_name='child',
            name='Important_notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='child',
            name='location',
            field=models.CharField(blank=True, choices=[('arrive', 'arrive'), ('left', 'left')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='teach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
    ]
